app:
  version: 1.0
  model: yolov8n.pt
camera:
  source: 2
  location: cam1
  stop_zone: [[196, 130], [364, 64], [221, 293], [425, 278]]
detection:
  stop_tolerance: 3
output:
  violation_file: violations.csv
settings:
  use_debug: false
