app:
  version: 1.0
  model: yolov8n.pt
camera:
  source: m2-res_480p.mp4
  location: cam1
  stop_zone: [[139, 116], [273, 37], [420, 171], [313, 307]]
detection:
  stop_tolerance: 3
output:
  violation_file: violations.csv
settings:
  use_debug: false
